#!/usr/bin/env bun
// Generates src/build/embedded.generated.ts so the compiled `quay` binary
// can run without a sibling `migrations/` or `config/` dir on disk.
//
// Embeds:
//   - All migrations/*.sql files (sorted, name+sql pairs)
//   - The shipped default config/ticket_schema.toml
//   - Build version: $QUAY_VERSION (release tags) or "dev" + short git SHA
//
// Run by `bun install` (via the `prepare` script) and `bun run build`.

import { readdirSync, readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { execFileSync } from "node:child_process";

const REPO_ROOT = fileURLToPath(new URL("..", import.meta.url));
const MIGRATIONS_DIR = join(REPO_ROOT, "migrations");
const SCHEMA_FILE = join(REPO_ROOT, "config", "ticket_schema.toml");
const OUT_FILE = join(REPO_ROOT, "src", "build", "embedded.generated.ts");

function readMigrations(): Array<{ name: string; sql: string }> {
  const files = readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort();
  return files.map((name) => ({
    name,
    sql: readFileSync(join(MIGRATIONS_DIR, name), "utf8"),
  }));
}

function readSchema(): string {
  return readFileSync(SCHEMA_FILE, "utf8");
}

function readGitSha(): string {
  try {
    const sha = execFileSync("git", ["rev-parse", "--short=7", "HEAD"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    const dirty = execFileSync("git", ["status", "--porcelain"], {
      cwd: REPO_ROOT,
      encoding: "utf8",
      stdio: ["ignore", "pipe", "ignore"],
    }).trim();
    return dirty.length > 0 ? `${sha}+dirty` : sha;
  } catch {
    return "unknown";
  }
}

export function formatBuildVersion(
  injectedVersion: string | undefined,
  sha: string,
): string {
  const baseVersion = injectedVersion?.trim() || "dev";
  return `${baseVersion}+${sha}`;
}

function buildVersion(
  env: Record<string, string | undefined> = process.env,
): string {
  return formatBuildVersion(env.QUAY_VERSION, readGitSha());
}

function tsLiteral(s: string): string {
  // JSON.stringify yields a valid TS string literal for any UTF-8 input,
  // escaping quotes/newlines/control chars correctly.
  return JSON.stringify(s);
}

function render(env: Record<string, string | undefined> = process.env): string {
  const migrations = readMigrations();
  const schema = readSchema();
  const version = buildVersion(env);

  const migrationLines = migrations
    .map(
      (m) =>
        `  { name: ${tsLiteral(m.name)}, sql: ${tsLiteral(m.sql)} },`,
    )
    .join("\n");

  return `// AUTO-GENERATED by scripts/embed.ts. Do not edit by hand.
// Regenerated on bun install (prepare hook) and bun run build.

import type { Migration } from "../db/migrate.ts";

export const QUAY_VERSION = ${tsLiteral(version)};

export const EMBEDDED_MIGRATIONS: readonly Migration[] = [
${migrationLines}
];

export const EMBEDDED_TICKET_SCHEMA = ${tsLiteral(schema)};
`;
}

function main(): void {
  mkdirSync(dirname(OUT_FILE), { recursive: true });
  writeFileSync(OUT_FILE, render(), "utf8");
}

if (import.meta.main) {
  main();
}
