import type { MissionControlTask } from './taskState';

export const SAMPLE_TASKS: MissionControlTask[] = [
  {
    id: 'abc123',
    ext: 'ITRY-1234',
    repo: 'quay-ui',
    title: 'Activity log timestamps drift after timezone change',
    branch: 'quay/itry-1234-tz-drift',
    state: 'pr-review',
    pr: 42,
    budget: 4,
    total: 5,
    latest: '5 inline comments on att #3',
    agent: 'gpt-5.3',
    age: '3m',
    attn: 'changes',
    attnTone: 'warn',
    authors: ['Mira Tonio'],
  },
  {
    id: 'mno345',
    ext: 'ITRY-1259',
    repo: 'erpc',
    title: 'Paginate the /events JSON-RPC endpoint',
    branch: 'quay/itry-1259-paginate',
    state: 'pr-open',
    pr: 53,
    budget: 2,
    total: 5,
    latest: 'CI build 4 of 6 passing',
    agent: 'gpt-5.3',
    age: '1m',
    authors: ['Alex Park'],
  },
  {
    id: 'klm234',
    ext: 'ITRY-1212',
    repo: 'iTRY-monorepo',
    title: 'Sanitize markdown in webhook payloads',
    branch: 'quay/itry-1212-md-sanitize',
    state: 'done',
    pr: 50,
    budget: 2,
    total: 5,
    latest: 'CI green - ready for reviewer',
    agent: 'gpt-5.3',
    age: '8m',
    authors: ['Alex Park'],
  },
  {
    id: 'def456',
    ext: 'ITRY-1241',
    repo: 'quay',
    title: 'Rate-limit the supervisor lock acquisition',
    branch: 'quay/itry-1241-rate-limit',
    state: 'running',
    pr: null,
    budget: 1,
    total: 5,
    latest: 'attempt 1 spawned',
    agent: 'claude-4.5-sonnet',
    age: '14m',
    authors: ['Mira Tonio'],
  },
  {
    id: 'yza567',
    ext: 'ITRY-1263',
    repo: 'iTry-contracts',
    title: 'Retry policy for failed deployment broadcasts',
    branch: 'quay/itry-1263-deploy-retry',
    state: 'running',
    pr: null,
    budget: 2,
    total: 5,
    latest: 'retry after crash',
    agent: 'claude-4.5-sonnet',
    age: '24m',
    authors: ['Tonio Vasquez'],
  },
  {
    id: 'rst012',
    ext: 'ITRY-1257',
    repo: 'quay-ui',
    title: 'Server-side pagination on configuration list',
    branch: 'quay/itry-1257-cfg-paginate',
    state: 'goal-completion-pending',
    pr: null,
    budget: 2,
    total: 5,
    latest: 'goal worker reported completion',
    agent: 'gpt-5.3',
    age: '6m',
    authors: ['Mira Tonio'],
  },
  {
    id: 'bcd890',
    ext: 'ITRY-1245',
    repo: 'quay',
    title: 'Tick respawn after worktree corruption regression',
    branch: 'quay/itry-1245-tick-respawn',
    state: 'pr-open',
    pr: 48,
    budget: 3,
    total: 5,
    latest: 'CI failed - waiting respawn',
    agent: 'gpt-5.3',
    age: '5h',
    attn: 'ci',
    attnTone: 'danger',
    authors: ['Mira Tonio'],
  },
  {
    id: 'efg123',
    ext: 'ITRY-1230',
    repo: 'erpc',
    title: 'Add trace headers to outbound JSON-RPC calls',
    branch: 'quay/itry-1230-trace-headers',
    state: 'pr-review',
    pr: 45,
    budget: 2,
    total: 5,
    latest: 'reviewer running...',
    agent: 'claude-reviewer',
    age: '4m',
    authors: ['Alex Park'],
  },
  {
    id: 'wxc345',
    ext: 'ITRY-1248',
    repo: 'iTRY-monorepo',
    title: 'Community PR - IDL formatting fixes',
    branch: 'community/idl-fmt',
    state: 'waiting_external_changes',
    pr: 44,
    budget: 1,
    total: 5,
    latest: 'changes requested - awaiting author push',
    agent: 'claude-reviewer',
    age: '2h',
    authors: ['Mira Tonio'],
  },
  {
    id: 'jkl012',
    ext: 'ITRY-1255',
    repo: 'hermes-agent',
    title: 'Token storage - final destination after SSO',
    branch: 'quay/itry-1255-sso-token',
    state: 'waiting_human',
    pr: 51,
    budget: 2,
    total: 5,
    latest: 'asked: which redirect after sso?',
    agent: 'claude-4.5-sonnet',
    age: '47m',
    attn: 'slack',
    attnTone: 'warn',
    authors: ['Quinn Lee'],
  },
  {
    id: 'vwx234',
    ext: 'ITRY-1260',
    repo: 'brix-landing',
    title: 'Mobile nav drawer - accessibility audit',
    branch: 'quay/itry-1260-nav-a11y',
    state: 'awaiting-next-brief',
    pr: null,
    budget: 1,
    total: 5,
    latest: 'orchestrator waiting next brief',
    agent: '—',
    age: '12m',
    authors: ['Quinn Lee'],
  },
  {
    id: 'cde678',
    ext: 'ITRY-1264',
    repo: 'iTRY-frontends',
    title: 'Wallet connect modal - error states',
    branch: 'quay/itry-1264-wc-errors',
    state: 'claimed-by-orchestrator',
    pr: null,
    budget: 1,
    total: 5,
    latest: 'orchestrator drafting next brief',
    agent: '—',
    age: '9m',
    authors: ['Alex Park'],
  },
  {
    id: 'pqr678',
    ext: 'ITRY-1262',
    repo: 'test-factory-code',
    title: 'Snapshot test for ZIP generator',
    branch: '—',
    state: 'queued',
    pr: null,
    budget: 0,
    total: 5,
    latest: 'waiting for worker slot',
    agent: '—',
    age: '6m',
    authors: ['Alex Park'],
  },
  {
    id: 'ghi789',
    ext: 'ITRY-1198',
    repo: 'brix-indexer',
    title: 'Reindex historical block range - out-of-memory loop',
    branch: 'quay/itry-1198-reindex-oom',
    state: 'non_budget_loop',
    pr: 37,
    budget: 5,
    total: 5,
    latest: 'non-budget retries exhausted',
    agent: 'gpt-5.3',
    age: '1d',
    attn: 'loop',
    attnTone: 'danger',
    authors: ['Mira Tonio'],
  },
  {
    id: 'hij456',
    ext: 'ITRY-1180',
    repo: 'quay-ui',
    title: 'Storybook stories for Field component',
    branch: 'quay/itry-1180-field-stories',
    state: 'worktree_error',
    pr: null,
    budget: 1,
    total: 5,
    latest: 'worktree corrupted',
    agent: '—',
    age: '2d',
    attn: 'worktree',
    attnTone: 'danger',
    authors: ['Tonio Vasquez'],
  },
  {
    id: 'stu901',
    ext: 'ITRY-1207',
    repo: 'iTRY-monorepo',
    title: 'Fix idempotency on subgraph deploy hook',
    branch: 'quay/itry-1207-subgraph-idem',
    state: 'merged',
    pr: 39,
    budget: 3,
    total: 5,
    latest: 'PR merged - 12 files',
    agent: 'gpt-5.3',
    age: '2h',
    authors: ['Mira Tonio'],
  },
  {
    id: 'nop567',
    ext: 'ITRY-1189',
    repo: 'quay',
    title: 'Telemetry batching - opt-out flow',
    branch: 'quay/itry-1189-telemetry-optout',
    state: 'cancelled',
    pr: null,
    budget: 1,
    total: 5,
    latest: 'operator cancelled',
    agent: '—',
    age: '3d',
    authors: ['Quinn Lee'],
  },
];
